address_bits        = 32

[L1]
level               = "L1"
cycles              = 1
sets_in_cache       = 256
blocks_per_set      = 4
bytes_per_block     = 16
write_allocate      = true
write_through       = false
eviction            = "fifo"

# [L2]
# level               = "L2"
# cycles              = 3
# sets_in_cache       = 2
# blocks_per_set      = 2
# bytes_per_block     = 4
# write_allocate      = true
# write_through       = true
# eviction            = "fifo"